### ISSUE TITLE
初学者的疑惑

### ISSUE THREAD

**Issue by PING020903** [xjz2517/Balance-car-based-on-stm32f407zgt6#1]
![无标题](https://github.com/xjz2517/Balance-car-based-on-stm32f407zgt6/assets/88314322/813db586-4ecd-4b16-a992-efc9885f58df)
原本只有"MPU6050.h"找不到，然后我添加到了工程中，添加了以后，就又出现了图中的这种情况。还有就是关于项目中头文件的创建，为什么我自己创建头文件它是不显示的呢？但在引用头文件的时候是可以找到头文件的，但就是无法引用头文件中自定义的类型

**Comment by xjz2517** [comment]
添加头文件以后,需要在魔法棒的C/C++选项卡添加对应的头文件的路径。

**Comment by PING020903** [comment]
> 添加头文件以后,需要在魔法棒的C/C++选项卡添加对应的头文件的路径。

感谢答疑🙏一开始确实不知道，都是直接放在当前目录中，杂乱无章
